### ISSUE TITLE
Import Action based on Solution Version 

### ISSUE THREAD

**Issue by tdashworth** [Capgemini/powerapps-packagedeployer-template#11]
**_This has not been tested yet._**

## Describe the bug
Looking at the method signature of [PackageTemplateBase.OverrideSolutionImportDecision](https://github.com/Capgemini/powerapps-packagedeployer-template/blob/5d1ccdecd577cfbce09809a2b0a7be1ec1c07de9/src/Capgemini.PowerApps.PackageDeployerTemplate/PackageTemplateBase.cs#L56), the logic in the method appears to be using the wrong `Version`s.

## To reproduce
Run the package deployer with different solution versions to understand the outcome.

## Expected behaviour
Honestly, not quite sure what the intent is. My belief is that the given flags (`UseUpdateForMajorVersions`, `UseUpdateForMinorVersions`, `UseUpdateForPatchVersions`) are used to determine whether the deployer will force an upgrade for the solution. 

## Additional context
[UserRequestedImportAction Enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.tooling.packagedeployment.crmpackageextentionbase.userrequestedimportaction?view=dynamics-deployer-ce-9)
[ImportAction Enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.tooling.packagedeployment.crmpackageextentionbase.importaction?view=dynamics-deployer-ce-9#Microsoft_Xrm_Tooling_PackageDeployment_CrmPackageExtentionBase_ImportAction_Import)

**Comment by ewingjm** [comment]
@tdashworth I believe we might need to take this logic and documentation out. I've tried this on project and it doesn't work as expected. It was based on my flawed understanding of what `UserRequestedImportAction.ForceUpdate` did. I assumed this was forcing an _update_ of the solution rather than an _upgrade_, but I believe the Package Deployer always does upgrades. Instead, this is when you want to force an update where you've got the same solution version or later already deployed.

**Comment by ewingjm** [comment]
But yes, it should also be using `inboundSolutionVersion` and not `packageSolutionVersion` 😄

**Comment by tdashworth** [comment]
Humm okay. Thanks for sharing your experience @ewingjm.
