### ISSUE TITLE
Revert ImportConfig.xml to v2 schema 

### ISSUE THREAD

**Issue by markcunninghamuk** [Capgemini/powerapps-packagedeployer-template#29]
## Describe the bug
Revert the schema to the previous schema. Will allow us to upgrade.

**Comment by ewingjm** [comment]
@markcunninghamuk just updated the name for additional context as I believe this applies to more than just `wordtemplates` - believe it was most configuration.

**Comment by ewingjm** [comment]
@markcunninghamuk @tdashworth I'm thinking if we're going to be introducing a breaking change here again we may as well make it worth our while. The original config schema could probably be improved. For example, instead of:

```xml
<processestoactivate>
  <processtoactivate  name="Case: Set Name"/>
</processestoactivate>
```

It seems like it would be more future-proof and introduce less duplication if we were to do something like:

```xml
<processes>
  <process name="Case: Set Name" state="active" />
</processes>
```

This then allows us to add additional configuration without needing to introduce another configuration element that duplicates the same processes.

**Comment by tdashworth** [comment]
The point was to revert back so no change would be required but I do prefer this option for future flexibility. 

I don't think the old scheme and upgradability should hold us back from bettering the configure for future expansion.

**Comment by tdashworth** [comment]
@ewingjm can this be closed? Maybe tag this with "won't fix"?

**Comment by ewingjm** [comment]
Ah, yes - good idea!
